### ISSUE TITLE
getting weights from static projections throws error

### ISSUE THREAD

**Issue by chanokin** [genn-team/pynn_genn#43]
When attempting to download weights I get the following error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  You cannot pull var 'g' from population 'projection_1_population0population1_0'

The code I'm running is:
```import pynn_genn as sim
backend = 'genn'
neuron_class = sim.IF_curr_exp

base_params = {
    'cm': 0.09,  # nF
    'v_reset': -70.,  # mV
    'v_rest': -65.,  # mV
    'v_thresh': -55.,  # mV
    'tau_m': 10.,  # ms
    'tau_refrac': 2.0,  # ms
    'tau_syn_E': 1.0,  # ms
    'tau_syn_I': 5.0,  # ms
}

timestep = 0.1
max_w = 0.01
start_w = max_w / 2.0
min_delay = 0.1

sim.setup(timestep, min_delay=min_delay,
          backend='SingleThreadedCPU'
          )

pre = sim.Population(10, sim.SpikeSourcePoisson(**{'rate': 10}))
post = sim.Population(100, neuron_class(**base_params))


synapse = sim.StaticSynapse(weight=1.0)
prj = sim.Projection(pre, post, sim.FixedProbabilityConnector(0.25),
                     synapse_type=synapse, receptor_type='excitatory')
# prj = sim.Projection(pre, post, sim.AllToAllConnector())
# prj = sim.Projection(pre, post, sim.OneToOneConnector())

sim.run(100)
weights = prj.getWeights(format='array')

sim.end()

```

**Comment by neworderofjamie** [comment]
What's happening is that PyNN GeNN is being _too_ smart and hard-coding the weight because it's  always 1.0. You can stop this happening by adding  ``and n in sub_pop.syn_pop.vars`` [here](https://github.com/genn-team/pynn_genn/blob/master/pynn_genn/projections.py#L182) but then you also need to get the return the right constant [here](https://github.com/genn-team/pynn_genn/blob/master/pynn_genn/projections.py#L203). Perhaps you could stash ``wum_params`` in the ``SubProjection`` [here](https://github.com/genn-team/pynn_genn/blob/master/pynn_genn/projections.py#L435) and search this if the variable isn't in ``sub.syn_pop.vars``
