### ISSUE TITLE
Problem installing pynn_genn

### ISSUE THREAD

**Issue by Hananel-Hazan** [genn-team/pynn_genn#6]
Thank you for sharing the code with the community. 

Install with setuptools using `python setup.py install` command, it finish with error:

> Installed /usr/local/lib/python3.6/dist-packages/pynn_genn-0.1.0-py3.6.egg
> Processing dependencies for pynn-genn==0.1.0
> Searching for pygenn
> Reading https://pypi.org/simple/pygenn/
> Couldn't find index page for 'pygenn' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.org/simple/
> No local packages or working download links found for pygenn
> error: Could not find suitable distribution for Requirement.parse('pygenn')

Thank you for your help

**Comment by neworderofjamie** [comment]
Thank you for your interest in this project - right now it is under heavy development so I wouldn't recommend trying to use it right now. However I'm hoping to make an initial 0.1 release in the next few weeks.

You issue is caused by PyNN-GeNN requiring GeNN itself to be installed. Essentially you need to:
1. Check out the 'python_wrapper_update_take_2' branch of https://github.com/genn-team/genn
2. Configure your GENN_PATH environment variable as described in the main documentation
3. Build a GeNN library by executing ``make -f lib/GNUMakefileLibGeNN DYNAMIC=1 LIBGENN_PATH=pygenn/genn_wrapper``
4. Build the Python bindings with ``python setup.py develop``

**Comment by tnowotny** [comment]
Can you ascertain where your cuda install is? Is it actually in /usr/local/cuda? Is your CUDA_PATH variable defined and pointing to the right location?

**Comment by Hananel-Hazan** [comment]
Yes, cuda installed at `/usr/local/cuda`.
Also, cuda default path variable in linux is CUDA_HOME, so I created another variable CUDA_PATH that point on the same location.

**Comment by neworderofjamie** [comment]
How odd - is there a ``cuda.h`` file in ``/usr/local/cuda/install``?

**Comment by Hananel-Hazan** [comment]
Those are the paths that `cuda.h` located on this system:
`/usr/include/nvidia-396/cuda/cuda.h`
`/usr/local/cuda-8.0/targets/x86_64-linux/include/cuda.h`

The system is Ubuntu 16.04.5 LTS

**Comment by neworderofjamie** [comment]
How interesting - I haven't seen it installed like that before. Is there a ``lib64`` directory under ``/usr/local/cuda-8.0/targets/x86_64-linux/`` containing ``libcuda.so`` and ``libcudart.so``?

**Comment by Hananel-Hazan** [comment]
`libcuda.so` is located 
`/usr/lib/x86_64-linux-gnu/libcuda.so`
`/usr/lib/i386-linux-gnu/libcuda.so`
`/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs/libcuda.so`

`libcudart.so` located 
`/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so`

**Comment by neworderofjamie** [comment]
Ok so you should export ``CUDA_PATH=/usr/local/cuda-8.0/targets/x86_64-linux/``. However I suspect it still won't work because it looks for cuda in lib64 on 64-bit systems so you'll need to hack line 105 of GNUMakefileLibGeNN. Could you please raise a bug on the GeNN github with the details of your system and, if you know, how you installed CUDA (runfile, ubuntu repository or NVIDIA repository)?

**Comment by Hananel-Hazan** [comment]
Thank you. 
I updated the `CUDA_PATH` as you mention and step 3 pass. 
However, I'm not sure if that what you suspected, step 4 failed, I'm getting:
> /usr/bin/ld: cannot find -lgenn_CPU_ONLY_DYNAMIC
> collect2: error: ld returned 1 exit status
> error: command 'c++' failed with exit status 1

**Comment by Hananel-Hazan** [comment]
Yes, I run step 4 right after running step 3 on the same place. `CUDA_PATH` maintain its definition.

**Comment by neworderofjamie** [comment]
Can you tell me what this command prints out?
``python -c "import os; print \"CUDA_PATH\" in os.environ"``

**Comment by Hananel-Hazan** [comment]
When running the line above I'm getting python running error. 
But, when running the following line 

> $ python3.6 -c "import os; print (os.environ['CUDA_PATH'])"
I'm getting:
> /usr/local/cuda-8.0/targets/x86_64-linux/

**Comment by tnowotny** [comment]
python 3 versus python 2 problem @neworderofjamie ?

**Comment by neworderofjamie** [comment]
I'm not sure - my incantation to get the CUDA path via python definitely wasn't python3 safe :disappointed: but the module installs ok on my python3.  @Hananel-Hazan could you try with Python2.7?

**Comment by neworderofjamie** [comment]
How very odd - can you try:
1. ``python setup.py clean -all``
2. manually changing ``cpu_only = False`` on line 10 of setup.py?

**Comment by Hananel-Hazan** [comment]
Here is the results:
1. `python setup.py clean --all`
> running clean
> removing 'build/temp.linux-x86_64-3.6' (and everything under it)
> removing 'build/lib.linux-x86_64-3.6' (and everything under it)
> 'build/bdist.linux-x86_64' does not exist -- can't clean it
> 'build/scripts-3.6' does not exist -- can't clean it

2.  changing `cpu_only = False`
> Traceback (most recent call last):
>   File "setup.py", line 35, in <module>
>     cuda_path = os.path.join(os.environ["CUDA_PATH"])
>   File "/usr/lib/python3.6/os.py", line 669, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'CUDA_PATH'

**Comment by neworderofjamie** [comment]
I'm afraid I'm a bit of ideas of what can be wrong - all I can think of
that could cause these symptoms is that you didn't *export* the CUDA_PATH.

**Comment by Hananel-Hazan** [comment]
If that was the case, this command 
`$ python3.6 -c "import os; print (os.environ['CUDA_PATH'])"`
would not output 
`/usr/local/cuda-8.0/targets/x86_64-linux/`

**Comment by neworderofjamie** [comment]
I just managed to reproduce this on my collegue's computer. I believe the problem is that you are running setup.py as sudo. If that is the case then your environment changes (I didn't know that!) so you have two options:
1. Don't run it as sudo - either use create a virtualenv (always a good idea) or use the ``--user`` flag to install in your home directory.
2. You can add a script to /etc/profile.d/ which exports CUDA_PATH i.e.
```bash
export CUDA_PATH=/usr/local/cuda-8.0/targets/x86_64-linux/
```

**Comment by neworderofjamie** [comment]
@Hananel-Hazan - did you get a chance to try this?

**Comment by Hananel-Hazan** [comment]
Yes, you right, sudo indeed change the environment . 
I'm actually trying to install it system-wide, that all users on the machine can enjoy running the software.
So I export all the relevant vars to sudo, that fixed the issue.

Thanks for the help

**Comment by neworderofjamie** [comment]
My pleasure! As I said the PyNN implementation is still very much work in progress, but I'd very much appreciate reports of any bugs you find. You should also expect to see large performance improvements in the near future!
